### ISSUE TITLE
python 3.8 syntax breaks 3.7 compatibility

### ISSUE THREAD

**Issue by ianccole** [pyvisa/pyvisa-py#346] opened 2023-01-03 13:52 UTC
https://github.com/pyvisa/pyvisa-py/blob/756152a97da3e7783d24b74fa09ae461eb92c787/pyvisa_py/tcpip.py#L1329

installing using pip3 install pyvisa-py on debian 10 (python 3.7.3) leads to no support for TCPIP

The above referenced line prevents the registration of TCP handlers TCPIPInstrSession, TCPIPSocketSession

**Comment by MatthieuDartiailh** [comment] 2023-01-18 21:51
This will be fixed in 0.6.1 (PR #349) since the origin of the regression is minor but please note that 3.7 is not officially supported anymore.

**Comment by MatthieuDartiailh** [comment] 2023-01-18 21:54
I will likely cut the release sometimes next week but if you can please test against main before

**Closed** 2023-01-25 20:08 UTC

**Comment by MatthieuDartiailh** [comment] 2023-01-27 14:13
0.6.1 is out
