### ISSUE TITLE
rm.list_resources() not showing TCPIP resources

### ISSUE THREAD

**Issue by CarlosOnera** [pyvisa/pyvisa-py#214] opened 2019-11-20 14:32 UTC
Hi,

I'm creating a test bench with several instruments and I'd like to automate as much as possible using pyvisa. When executing 

rm = pyvisa.ResourceManager()
print(rm.list_resources())

Only USB instruments are shown; I've tried already a few combinations like
rm.list_resources(query='?*::INSTR')
and
print(rm.list_resources(query='TCPIP::*'))
without avail.

I am, however, able to connect to the instrument and get IDN using the rm.open_resource() function with TCPIP (VXI-11).

Is there anything in particular that I would need to do to be able to see the TCPIP instruments?

I'm using Python 3.8

**Comment by MatthieuDartiailh** [comment] 2019-11-20 14:37
That capability is not yet implemented in pyvisa-py. Since this issue is a duplicate of #165 I will close it. If you have time you can have a look at implementing it, #165 has a reference for you to look at.

**Closed by MatthieuDartiailh** 2019-11-20 14:37 UTC
