### ISSUE TITLE
ValueError: Please install linux-gpib to use this resource type. No module named 'gpib'

### ISSUE THREAD

**Issue by Rozakos** [pyvisa/pyvisa-py#191] opened 2019-06-12 08:57 UTC
I am trying write some commands to Keithley 2000 multimeter, but i am getting that specific error, any ideas?

``Traceback (most recent call last):
  File "C:/PyTests/Keithley.py", line 4, in <module>
    keithley = rm.open_resource("GPIB::12")
  File "C:\PyTests\venv\lib\site-packages\pyvisa\highlevel.py", line 1724, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\PyTests\venv\lib\site-packages\pyvisa\resources\resource.py", line 209, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\PyTests\venv\lib\site-packages\pyvisa\highlevel.py", line 1681, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\PyTests\venv\lib\site-packages\pyvisa-py\highlevel.py", line 194, in open
    sess = cls(session, resource_name, parsed, open_timeout)
  File "C:\PyTests\venv\lib\site-packages\pyvisa-py\sessions.py", line 170, in __init__
    raise ValueError(msg)``

**Comment by MatthieuDartiailh** [comment] 2019-06-12 13:55
Duplicate of https://github.com/pyvisa/pyvisa/issues/421

**Closed by MatthieuDartiailh** 2019-06-12 13:55 UTC
